auto_start_break: true
auto_start_work: false
dark_theme: true
long_break_interval: 4
long_break_mins: 15
long_break_msg: Take a long break
notify: true
session_cmd: ""
short_break_mins: 5
short_break_msg: Take a breather
sound: ""
sound_on_break: false
work_mins: 25
work_msg: Focus on your task
